### ISSUE TITLE
A question about dataset

### ISSUE THREAD

**Issue by QzzIsCoding** [Izecson/fairseq-editor#1]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
   Hi, thanks for sharing the coding! I want to implement the EDITOR using English-Chinese datasets. And I have some question: 
  1. What form of dataset is used in training? 
  2. Does it require constraint terms?
  3. Is only the test input file with soft lexical constraints enough?
  If it's convenient, can you provide me with an example of input for English-Japanese?
#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by weijia-xu** [comment]
Hi,

To answer your questions:
1. EDITOR can be trained on standard parallel data consisting of parallel source and target sentences. You can follow [this guideline](https://github.com/Izecson/fairseq-editor/tree/main/examples/translation) to prepare your training data.
2. No, it doesn't require constraint terms during training.
3. During inference, each line of the input file contains a source sentence and a constraint sequence separated by <sep>. An example of input for English-Japanese is:
_Hello world \<sep\> 世界_
